### ISSUE TITLE
Merge PR if the PR is 24 hours old

### ISSUE THREAD

**Issue by Madhu-1** [Mergifyio/mergify-engine#1065]
If the PR is at least 24/48 hours old and as at least have one approval from the maintainer the mergify should merge the PR.

is this something already possible with Mergify? or is it possible to support this configuration?

this will be really helpful for the Maintainers if some maintainer is not there for a while, we don't want to keep waiting on approval to merge the PR and we want to avoid manual merging of PR.

**Comment by jd** [comment]
Hi @Madhu-1,

It's not possible right now unfortunately, but we have already an issue opened to track that: #335
