### ISSUE TITLE
Clarify permissions required to run backport command

### ISSUE THREAD

**Issue by ezimanyi** [Mergifyio/mergify-engine#1070]
## Overview

We've recently started using Mergifyio to handle our backport and merge workflows.  In general things are working really well!  One issue we've noticed is that some users are unable to run the `backport` command and get an error message `[user] is not allowed to run commands`.

I wasn't able to find documentation anywhere on what permissions on the repo are required to allow a user to run the `backport` command.  Would it be possible to include this somewhere in the documentation?

Ideally for our workflow, anyone would be able to run `mergify backport` as that will just open a pull request, and we're using merge permissions to gate whether that pull request actually gets merged.

Some more details:
* We're an open source project where often end-users want bug fixes backported from `master` to a particular `release-*` branch.
* A small group of release managers have access to the `release-*` branches; we have mergify configured to only merge pull requests to these branches if approved by a release manager.
* Ideally anyone would be able to request a backport by running the `backport` command on a pull request against `master` to open a backport PR against a `release-*` branch.
  * Even though mergify blocks this, anyone with a Github account could manually do the backport and open the PR, so it's not clear to me the benefit of blocking PR creation.
* Once the backport PR is opened (whether manually or by mergify), branch protection rules and mergify config only allow it to be merged after approval by a release manager.

The only part of the above workflow that's not working is that most people can't request backports, so either need to comment on the PR tagging a release manager to ask them to run the command, or they need to manually do the backport and open the PR.  It's a much easier workflow for the small group of release managers if they can review PRs that are already open/ready and decide whether to merge, instead of being pinged in multiple channels to help with the backport process itself.

## Summary

We'd love if there was a way to allow any Github user to request a backport via the `backport` command, perhaps gated by a setting in the mergify config.

In the absence of that, it would be great to document what permissions are required to run that command, as I was unable to find that anywhere in the current documentation.

**Comment by jd** [comment]
Thank you so much for the detailed report!
All the commands make sure for now that the user requesting it has write permissions. We must document it I agree.

We could also relax this for some commands probably, good suggestion.

**Comment by kevinawoo** [comment]
👍 for relaxing the permissions, or at least giving users the option to relax it per `.mergify.yml` config
