### ISSUE TITLE
Ability to force backport from Commands

### ISSUE THREAD

**Issue by leseb** [Mergifyio/mergify-engine#1129]
Most of the time I don't want to create a backport PR if cherry-pick failed so `ignore_conflicts` is `False`. Sometimes, however, I would like to be able to create a backport PR with a Command like:

`@Mergifyio backport release-1.3 --ignore_conflicts`

I know the current format for commander only accepts parameters and no arguments, hence the `--` suggestions, whatever is best.

It's handy so that I don't have to edit the `.mergify.yml` config file.

**Comment by jd** [comment]
Force is now the default so that will work.

**Comment by leseb** [comment]
Yes just noticed! Thanks for reverting.
