### ISSUE TITLE
Write better merge commit message

### ISSUE THREAD

**Issue by Elv13** [Mergifyio/mergify-engine#113]
Following the comments on https://github.com/awesomeWM/awesome/pull/2300, I wonder if there is a better way to handle merge commits.

The issue that gave rise to that PR is that some people see those commits as pure noise. They only allow to tell which commits were part of a pull request. In itself, along with some `git-blame` Voodoo, is useful in itself (to me), but could Mergify.io add more value here?

Given (I guess) you can write the merge commit message, I wonder if adding some sort of template would add value to both Mergify as-a-product and to the `git log` itself. The template could carry more metadata about the PR such as:

 * Who approved it
 * Each GitHub CI service summary one liner (and if they passed, of course)
 * Some user comments (like auto-append the codecov.io coverage summary
 * The date the PR was opened
 * The username of the PR author (it isn't necessarily the same as the commit author)
 * The shortlog of each commit?
 * The PR description
 * The PR name
 * "Fetch this magic URL and append the content" for user-defined extensions?

This isn't a "I WANT THIS NOW!!!11!" kind of wish. It's just an idea how to make your service more useful and create more value for everybody.

**Comment by sileht** [comment]
It's possible now cf: https://blog.mergify.io/using-templates-in-your-messages/

If new attributes are needed fill free to open new issue.
