### ISSUE TITLE
Mergify failed to merge the pull request: Resource not accessible by integration

### ISSUE THREAD

**Issue by grondo** [Mergifyio/mergify-engine#1181]
We've been consistently getting this error the last couple days

https://github.com/flux-framework/flux-core/pull/2995/checks?check_run_id=770134714
```
Mergify failed to merge the pull request
GitHub error message: Resource not accessible by integration
```

Verified that mergifyio is still enabled for this repo, and rebasing does seem to work.
Any suggestions on how to debug?

**Comment by sileht** [comment]
Usually, it's when our Github App doesn't have required permissions on the repository, but I check the permissions, and they looks fine. I take a closer look at it.

**Comment by sileht** [comment]
Did you configure any "Branch protection"? and restrict users that can push to the repository?

**Comment by grondo** [comment]
Thanks! We haven't made any recent changes to branch protection of which I'm aware, but I'll double check.

**Comment by grondo** [comment]
We have branch protection enabled, but do not restrict users or team that can push to the branch. (and I'm not sure how to check, but I do not believe branch protection settings have been changed recently, but mergify was working as recently as last week)

**Comment by grondo** [comment]
I am going to try removing then re-installing Mergify on our project to see if that helps.

**Comment by grondo** [comment]
We had to manually merge the PR referenced above. Mergify was then able to merge a few follow on PRs successfully, but now we've got another PR with the same error (we'll likely have to merge manually)

https://github.com/flux-framework/flux-core/pull/3016/checks?check_run_id=796401357

Any advice on how to diagnose the underlying issue would be appreciated. We already tried uninstalling and re-installing mergify on our project.

Thanks!

**Comment by sileht** [comment]
We reach the GitHub support about this issue, this occurs when files are changed inside  `.github/workflows` directory, this is forbidden for GitHub App for security reason by GitHub.

So, now we have catch this particular and print an understandable error message.
