### ISSUE TITLE
Feature Request: configurability of which use's account handles rebase action

### ISSUE THREAD

**Issue by mwachs5** [Mergifyio/mergify-engine#1237]
Currently mergify docs say:

"Mergify will use a token from one of the repository member to force-push the branch. GitHub Applications are not allowed to do that so. This is a GitHub limitation that we already have reported — there is not much Mergify can do about that. In order to make this works, Mergify randomly picks and borrows a token from one of your repository member and uses it to force-push the rebased branch. The GitHub UI will show your collaborator as the author of the push, while it actually has been executed by Mergify."

Rather than randomly picking a user it would be nice if that could be set by the mergify configuration.

**Comment by jd** [comment]
Good point — we already had that on our internal roadmap, and I'll your vote to it. That's one of the next items on our list.
