### ISSUE TITLE
merging master to a PR

### ISSUE THREAD

**Issue by Borda** [Mergifyio/mergify-engine#1307]
about today we have observed strange behavior that Mergigy instead merging or to target branch (as it was doing until now) is merging target branch to the PR, see events:
- https://github.com/PyTorchLightning/pytorch-lightning/pull/2873#issuecomment-670774376
- https://github.com/PyTorchLightning/pytorch-lightning/pull/2872#issuecomment-670774359

**Comment by sileht** [comment]
In fact, it does both, as you configured in .mergify.yml, it first merges target branch into the PR (because of `strict: true`), and when all conditions match it creates a squash commit and merge it into the target branch (because of `method: squash`).

**Comment by Borda** [comment]
Ok, but it seems to be happening also for draft PRs, is it intended or how can we fiter them out?

**Comment by sileht** [comment]
you can filter out draft PR by adding the condition: `-draft`
