### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by tw15egan** [Mergifyio/mergify-engine#1316]
Hey y'all! We've been loving the integration and have been using it for automating our tutorial repo based on a few conditions. 

Basically, I set up some simple tests in CricleCI that are used in our `.mergify.yml` to either close and append a label (`status: complete`), or if there are errors, keeps it open and adds a label `status: needs correction`

It seems like 1 week ago, the integration stopped. It's not showing up in the `checks` section anymore either. Integration is still installed, and I verified that the config is still valid via the dashboard. 

Any ideas why this would have stopped working recently?

Config: https://github.com/carbon-design-system/carbon-tutorial/blob/master/.mergify.yml

Working PR's: https://github.com/carbon-design-system/carbon-tutorial/pulls?page=2&q=is%3Apr+is%3Aclosed

Non-working 🙁 : https://github.com/carbon-design-system/carbon-tutorial/pulls?q=is%3Aopen+is%3Apr

**Comment by sileht** [comment]
This was a read timeout issue. https://github.com/Mergifyio/mergify-engine/commit/5131426ecd02eebbbc79d7afa30c7533aacca237

**Comment by tw15egan** [comment]
Thanks for the quick fix! ❤️
