### ISSUE TITLE
Github Branch Protections and smart strict merging can cause deadlock

### ISSUE THREAD

**Issue by melink14** [Mergifyio/mergify-engine#1372]
As per the example configs, we setup a mergify config that should merge whenever Github branch protections are satisfied.

We also setup `smart+fasttrack` strict mode in order to avoid breakages in master.

This seemed to work well, but it ordered the PRs such that the ones waiting on approval were ahead of the the ones which were ready (except needing to be updated) and thus the queue never moved (until I approved the waiting PRs).

Feature Request: Send PRs to the back of the queue if they are waiting on Branch Protections (there may be other similar interactions).

Current workarounds:
- Don't use smart and waste some cylces. This is not too uncommon for bots in Github universe but seems unnecessary.
- Add an approvals condition to mergify since that's unlikely to change and is the only condition that requires human involvement.

Do devs have an opinion on what course of action is canonical?

Thanks!

**Comment by jd** [comment]
Thanks for the report! One of the issues that pop up often is #448. Unfortunately, the GitHub API does not offer a documented and reliable way to know when the branch protections are satisfied.

We'll try to implement a workaround in the future, we'll see how that goes. I know @sileht has a few ideas. :)

**Comment by sileht** [comment]
The workaround is live now, the queue should not block anymore.

**Comment by jd** [comment]
Closing this, feel free to reopen if that happens again.
