### ISSUE TITLE
Trigger action if new pull request merged

### ISSUE THREAD

**Issue by prayank23** [Mergifyio/mergify-engine#1373]
Is it possible to automate the below mentioned things using mergify?

1. Check if a new PR is merged
2. Read content mentioned in "comments" and save it in a variable
3. Run a python script and use the variable (python code will be on local machine for testing and remote server later)
4. Python code returns some output which needs to be added as comment in the pull request which was merged and used in this case

**Comment by jd** [comment]
That's definitely not possible. You could use GitHub webhook to trigger your script, or Mergify webhook if we support then one day :)
