### ISSUE TITLE
Don't report the status check as "failing" when mergify is not enabled in some pr

### ISSUE THREAD

**Issue by Liu233w** [Mergifyio/mergify-engine#146]
Hi,
When mergify is not enabled in some pull request, it will report "failing", eg
![default](https://user-images.githubusercontent.com/16333687/44090133-b719f3d8-9ffb-11e8-999c-45a70d516655.png)

It would be great if the status check is not shown in this case. Because I also use other bots ([dependabot](https://app.dependabot.com/), for example). Some of them may not proceed until all the status check report "success".

**Comment by jd** [comment]
This is not accurate anymore with v2.
