### ISSUE TITLE
Pull PR requirements from GitHub settings

### ISSUE THREAD

**Issue by edahlseng** [Mergifyio/mergify-engine#149]
Most of the settings for Mergify are duplicates of GitHub branch protection settings. In order to avoid duplication, it would be awesome to be able to set the Mergify settings to pull from GitHub instead of specifying them again in the config.

**Comment by jd** [comment]
That would work for the initial configuration proposal at least. Since we're adding finer-grained rules for auto-merge, that might be confusing to only support those of GitHub.

**Comment by edahlseng** [comment]
Are those finer-grained rules going to be a superset of the GitHub rules? If so, maybe it makes sense to use GitHub rules + rules added on top by the Mergify configuration?

Thinking about this more, the main reason that I suggested pulling the requirements from GitHub was because we have several different repos that are all managed by a single GitHub configuration specified within Terraform. Adding Mergify scared me a bit as I realized that there would be a ton of extra duplication. Perhaps there's a way that Mergify configurations could be shared/pulled in from another location or repo to share configuration?

**Comment by jd** [comment]
For example, GitHub rules are per-branch, whereas we'd like to have Mergify rules per-pull request. Therefore, it's gonna be difficult e.g. to use a " reviewers" restriction from GitHub on a branch whereas you might have a Mergify rule that says "if the pull request comes from XYZ, 1 review is enough" — if you apply GitHub restriction, then it'll block the PR coming from XYZ.

> Perhaps there's a way that Mergify configurations could be shared/pulled in from another location or repo to share configuration?

You could actually replace GitHub branch protection configuration from Terraform with a Mergify configuration generator. Then you'd let Mergify apply the GitHub restriction itself (it does that, at least for now) and you'll have full control of whatever your merge rules are. :)

**Comment by edahlseng** [comment]
Thanks for the comments @jd. Now I understand where you're trying to take Mergify, and why pulling from GitHub doesn't quite fit into that vision. I still think there's an opportunity to cut down on duplication with the Mergify configs, but I'll open a separate issue for that discussion!

**Comment by edahlseng** [comment]
Thinking about this more, I feel like the best option may be to use Terraform to block all merges _except_ for the Mergify bot. This means that Mergify would become the single source-of-truth for merge conditions. Coupled with the possibilities open for discussion in #150, I feel like this could be a very sane workflow!
