### ISSUE TITLE
commented-reviews-by condition not behaving as expected 

### ISSUE THREAD

**Issue by benorgan** [Mergifyio/mergify-engine#1547]
We are using a rule based on this example https://docs.mergify.io/examples.html#require-all-requested-reviews-to-be-approved to ensure all reviewers have approved the PR before it is automatically merged. 

However, this fails when a reviewer has left a comment, even if they approved the PR along with the comment. As the screenshot shows, it's the `#commented-reviews-by=0` condition which is not passing:

![image](https://user-images.githubusercontent.com/5031585/98043449-12c66500-1dda-11eb-80e9-ff70d9430074.png)

Removing this `commented-reviews-by` condition means that PRs could get merged when one reviewer has approved and the other has only left a comment (but not approved), which is not desirable.

**Comment by jd** [comment]
Hi!

> However, this fails when a reviewer has left a comment, even if they approved the PR along with the comment.

Indeed, that might be what GitHub returns part of its API unfortunately.

I'll update the documentation example to be more clear about that.

The question would be, what would you like to do exactly if you're not able to do it with the current conditions?

**Comment by benorgan** [comment]
I think the best solution would be to allow a condition where we can check the `approved-reviews-by` matches the number of reviewers, then we could do away with the `=0` checks for changes, comments and review requested. 

I'm not familiar with the GitHub API so not sure what is and isn't possible.

**Comment by benorgan** [comment]
I suppose the other way we could do it is to automatically add labels based on the number of reviewers and then enforce the number of reviews based on labels?

**Comment by jd** [comment]
To give some context, a review request disappears as soon as the code is reviewed, so there's no way to know if a review was done based on a request.

In general, I think using`#review-request=0` is good enough; if there are 0 review requests waiting (no little orange dot in the UI) then it'd match. It's not a sufficient condition, but it's a good safeguard against merging PRs that have not been reviewed by everyone requested.

WDYT?

**Comment by benorgan** [comment]
`#review-request=0` would also be true when there are no reviews requested I think, so we'd need another condition to prevent merges without any reviewers. 

In the end we solved this by adding a label when there are multiple reviews requested and then having 2 rules (one for single reviewer and one for multiple) using the label to ensure the correct number of approvals were received.

**Comment by jd** [comment]
Yes, that's why I wrote _it's not a sufficient condition_ 😉 
Good idea using labels, I'll update the documentation about all this. Thank you!
