### ISSUE TITLE
Mergify is seeing Check failures as success

### ISSUE THREAD

**Issue by SachinShekhar** [Mergifyio/mergify-engine#1665]
Have a look at this PR: https://github.com/ServerlesslyStack/Serverlessly/pull/19

`Matrix Test / Test on macos-latest with node.js v12 (pull_request)` has clearly failed, if you look at [Mergify Summary for this PR](https://github.com/ServerlesslyStack/Serverlessly/pull/19/checks?check_run_id=1599548369), `check-success=Test on macos-latest with node.js v12` has passed. Because of this, all rules which contain `Test on macos-latest with node.js v12` are misbehaving.

This is clearly a bug.

**Comment by SachinShekhar** [comment]
My best guess: It's happening because `Matrix Test / Test on macos-latest with node.js v12 (push)` has passed (PR got stuck in the process of merging after update from base branch; possibly, that's why push version also ran).

If that's the case, how would you deal with such scenario? The documentation doesn't say anything about such scenario.

**Comment by jd** [comment]
Yes, that's indeed the case. Mergify is not able to differentiate the two items and they are considered as one.

The safest best is to not run the action twice on different events there for now.

On the Mergify side, we'd need to improve our support for GitHub actions in that regard.

**Comment by SachinShekhar** [comment]
I guess I will rename the job for push event for now.
