### ISSUE TITLE
Mergify Not merging automatically into master

### ISSUE THREAD

**Issue by joesan** [Mergifyio/mergify-engine#1763]
I have added a mergify.yaml file to one of my public projects, but I could not make it automatically merge on successful travis ci builds. Any idea what I'm missing? Here is my mergify.yml:

https://github.com/joesan/plant-simulator/blob/master/.mergify.yml

I do not have any strict checking configured in against my GitHub project which would prevent this auto merge into master. Any ideas what I'm missing?

**Comment by sileht** [comment]
There are no status/check-runs named `build` on your pull request.

I guess you want `status-success=continuous-integration/travis-ci/pr`

**Comment by joesan** [comment]
Thanks for pointing out, but where in the mergify documentation could I see that?

**Comment by sileht** [comment]
https://docs.mergify.io/conditions.html#implementing-or-conditions

**Comment by joesan** [comment]
Cool! Thanks for that! I will close this issue!
