### ISSUE TITLE
'update' action seems to be not consistent

### ISSUE THREAD

**Issue by Borda** [Mergifyio/mergify-engine#1872]
We have defined `update` action and it seems to work with some PRs but not for all, could it be like to presence of config in the target branch?
So we have updated our `master` branch with the actual mergify config which I was debugging in mergify UI

this PR is going to `master` and action was executed: https://github.com/PyTorchLightning/pytorch-lightning/pull/5607
![Screenshot 2021-01-22 at 11 24 20](https://user-images.githubusercontent.com/6035284/105479427-b9692600-5ca4-11eb-8194-9fece48cfe40.png)

this PR is going to `release/1.2-dev` and action was NOT executed: https://github.com/PyTorchLightning/pytorch-lightning/pull/5596
![Screenshot 2021-01-22 at 11 24 42](https://user-images.githubusercontent.com/6035284/105479541-ddc50280-5ca4-11eb-8422-7dae56dd8ceb.png)

When I check the conditions in UI in both cases it shall be triggered...

**Comment by sileht** [comment]
On PyTorchLightning/pytorch-lightning#5596 rules said to update the PR only if the PR conflict.

You have fixed the configuration here:
https://github.com/PyTorchLightning/pytorch-lightning/commit/015cb2f33eafdf3353e934f2e1872f507f4bdd96e

But Mergify didn't re-run automatically since nothing change on this PR.

You can use `@Mergifyio refresh` to re-trigger Mergify with the updated configuration.

**Comment by Borda** [comment]
OK, you say that mergify is event-driven, so why in UI is a clock which stated when the next update comes?
like this message in the UI: `Nothing planned to be merged. Next refresh at 1:51 PM`
So is there another way to propagate updates on mergify config? It can be quite painful after each cofing update if you need to check all open PRs and manually ping the bot... imaging large repos with hundreds of PRs

**Comment by jd** [comment]
You're looking at `Queues` in the dashboard, which as its names states, shows merge queues. 😉 

Re-evaluating all open PR in a large repo would exhaust GitHub API rate limit anyway, so there's little chance we could do that 😢
