### ISSUE TITLE
Don't clobber branch protection settings in GitHub

### ISSUE THREAD

**Issue by jmandel** [Mergifyio/mergify-engine#194]
For https://github.com/hl7/fhir, we'd like to have a large group of committers, and only use Mergify for a subset of them. But currently Mergify reaches in and changes our GH branch protection settings to remove merge access for the "fhir-committers" team each time a PR is created.

The desired behavior is to configure branch protection in GH for the entire "fhir-committers" team, and then to use Mergify as an *extra* layer on top, enabling Mergify only for the "fhir-committers-mergify" team. But effectively Mergify is propagating protection settings into GH's branch protection config automatically, without recourse.

**Comment by jd** [comment]
Yeah, currently Mergify will take over the GH branch protection settings and apply automerge on top of that. That will be solved with engine v2.

**Comment by jd** [comment]
The v2 engine that has been merged does not mess with protection settings anymore. Closing.
