### ISSUE TITLE
Allow to specify merge method to use

### ISSUE THREAD

**Issue by jd** [Mergifyio/mergify-engine#22]
The current merge method is always `rebase` according to https://github.com/Mergifyio/mergify-engine/blob/master/mergify_engine/gh_pr.py#L121 (and `merge` on fail). Some users would like to specify which merge method should be used.

Source: https://www.indiehackers.com/forum/82ed7152d5?commentId=-LBbIoieYoJQzEERJEYz

**Comment by sileht** [comment]
We are good with this one: 229115421b2d222dc14e47c3883990a08608a578
