### ISSUE TITLE
Does Engine v2 ready for work yet?

### ISSUE THREAD

**Issue by guy-lud** [Mergifyio/mergify-engine#222]
Hey Guys.

We've been trying to work a bit with v2 and we always get an exception ?

**Comment by jd** [comment]
@guy-lud do you have some log or PR number to provide?

**Comment by jd** [comment]
That looks good to me. We can definitely look into it if you have some log or repo name. :)

**Comment by guy-lud** [comment]
Sorry Guys, We've left this project for some time. so i won't be able to post the error.

Anyway can you please tell us when V2 will be released to production ?

**Comment by jd** [comment]
It'll be available starting Monday 15th October.
