### ISSUE TITLE
Mergify not Auto Mergiing PR's into master

### ISSUE THREAD

**Issue by joesan** [Mergifyio/mergify-engine#2281]
## Expected Behavior
Mergify should merge PR's automatically into master branch and close the PR.

## Actual Behavior
Having configured Write access to Mergify, I do not see why Mergify would not merge changes / PR's automatically into my master branch. It was indeed working before, doing auto merge into master and closing PR's, but all of a sudden this ceased to work.

## Specifications

  - Pull Request URL:  https://github.com/joesan/plant-simulator/pull/105
  - Mergify Config URL: https://github.com/joesan/plant-simulator/blob/master/.mergify.yml

**Comment by jd** [comment]
It's rather clear if you go there:
https://github.com/joesan/plant-simulator/pull/105/checks?check_run_id=2176533053
![Screenshot 2021-03-24 at 08 46 33](https://user-images.githubusercontent.com/2644/112273284-76640880-8c7d-11eb-83ec-e2a1bfa5468f.png)

You configured a CI as being Travis but I don't see any CI being reported to your pull request. Are you using Travis or did you just copy/paste that line from the example? If you're not using a CI, you can remove this condition.

**Comment by joesan** [comment]
I'm using Travis and here is the Travis build for this particular PR: https://travis-ci.org/github/joesan/plant-simulator/builds/764106441

**Comment by jd** [comment]
Travis is not reporting anything to GitHub:
![Screenshot 2021-03-24 at 13 53 13](https://user-images.githubusercontent.com/2644/112313575-4da53880-8ca8-11eb-8f33-4fd86d330383.png)

There might be some misconfiguration of your Travis and GitHub integration.

**Comment by joesan** [comment]
![image](https://user-images.githubusercontent.com/3284487/112321319-2e120e00-8cb0-11eb-8add-23d335ea592a.png)

Very strange. I have given access to Travis to send Notifications upon successful build. Don't understand why it fails!

**Comment by joesan** [comment]
I have moved from Tavis to GitHub Actions and the auto merge works flawlessly. Seems Travis was not reporting the status back correctly upon successful builds.
