### ISSUE TITLE
V2 Questions

### ISSUE THREAD

**Issue by edahlseng** [Mergifyio/mergify-engine#232]
I'm excited for Mergify V2! After looking through the documentation in #200, I have a couple questions:
* Is there a parallel to the `enforce_admins` option from V1?
* Is there a way to require every requested review to be completed? The use case that I'm encountering is that we'd like to require that every PR has at least 1 approved review, but that if 3 people are requested for review, then all 3 of them should also have approved the PR.

**Comment by jd** [comment]
Hi @edahlseng!

- That depends what you use it for. You can still use it as it's an option in GitHub branch protection; you can enable those protections yourself. Just be careful they don't conflict with your Mergify configuration!
- That's not possible yet, as there's no way to match `approved-review-by` and `review-requested`. For now. That's something that could be easily be added!

**Comment by edahlseng** [comment]
@jd Thanks for the response!
* So to confirm, Mergify will no longer override that setting (if we choose to turn it on in GitHub branch protection)?
* Sounds good, I'll see if I can put up a PR for that today!

**Comment by jd** [comment]
Indeed, v2 does not mess with branch protection at all. You have to manage those yourselves now.

For matching variables, it's likely you'd have to build a new custom variable somehow in `mergify_engine.mergify_pull.MergifyPull.to_dict` that represents this matching.

**Comment by jd** [comment]
@edahlseng IIUC your second request is https://github.com/Mergifyio/mergify-engine/issues/66 basically, right?
