### ISSUE TITLE
Can't enable "strict" mode on my repository

### ISSUE THREAD

**Issue by Gentux** [Mergifyio/mergify-engine#24]
Hi,

I just tried to update my **mergify** configuration according to [documentation](https://doc.mergify.io/strict-workflow.html). But it fail and I don't see where I messed up :)

https://github.com/Gentux/imap-cli/pull/22

Can you tell me what's wrong in my configuration file ?

**Comment by sileht** [comment]
The configuration looks good. What is confusing here is that the reported error message is about the file on the master branch, so it doesn't contains the change from the PR.

**Comment by jd** [comment]
@sileht anything we can improve for it to be clearer? Should we add something in the doc at worst?
