### ISSUE TITLE
Does mergify Support Timer ?

### ISSUE THREAD

**Issue by AhmedMItman** [Mergifyio/mergify-engine#2460]
## Expected Behavior
We expected mergify supports timer, for example after 3 days mergify automatically merge PR to base.
So, We expected there is and option in the Configuration file for setting that period ( 3 days ).
Does it exists ? It will be a great if exists :pray:

**Comment by sileht** [comment]
Not yet, but that something we have on our backlog. You just increase its score :)

**Comment by AhmedMItman** [comment]
@sileht thanks :rocket:

**Comment by sileht** [comment]
This has been implemented, you can now write conditions like:

`merged_at>=3 days`
