### ISSUE TITLE
Allow to track dependencies between PR

### ISSUE THREAD

**Issue by jd** [Mergifyio/mergify-engine#25]
It's common for some projects to build pull requests that have dependency. It'd be nice if Mergify was able to track those dependencies and merge the PR accordingly, in the right order, following the direct (acyclic) graph.

**Comment by jd** [comment]
This has been requested in https://github.com/isaacs/github/issues/959

**Comment by sileht** [comment]
https://github.com/Mergifyio/mergify-engine/pull/2619

**Comment by jd** [comment]
Closing this as it works.
We still want at some point to have cross-repo, but that's a good first step.
