### ISSUE TITLE
Allow to merge dependabot pr's that update github actions workflows.

### ISSUE THREAD

**Issue by AraHaan** [Mergifyio/mergify-engine#2507]
## Expected Behavior
The ability to give mergify the permission to merge dependabot pr's that updates actions in ``.github/workflows``.

I would at least like the option to be able to give the bot permission to merge them if they change workflows.

## Actual Behavior
It keeps on trying to merge, until it says that it cannot do it after over 1k times.

## Steps to Reproduce the Problem

  1. Setup merge rules like the ones I link below.
  2. Get updates through dependabot for github actions.
  3. Notice Mergify spams it up trying to invoke the rule to actually merge it constantly. 

## Specifications

  - Pull Request URL: https://github.com/Elskom/GitBuildInfo.SourceGenerator/pull/12 and https://github.com/Elskom/Sdk/pull/200
  - Mergify Config URL: https://github.com/Elskom/GitBuildInfo.SourceGenerator/blob/main/.github/mergify.yml

**Comment by jd** [comment]
This is a GitHub limitation. They don't allow a GitHub App to merge such a PR.

**Comment by sileht** [comment]
It keeps retrying because you remove the label and try to merge the PR at the same time. This can't work, `.github/workflows` or not. You may get things merged most of the time with such configuration, but this may fail from time to time.

Also we can't do anything about the directory `.github/workflows`, it's a security measure taken by GitHub.

**Comment by AraHaan** [comment]
Actually you can override it using permissions like how PAT's can be set to allow it. I guess it could be made where if it sees that anything in ``.github/workflows`` is changed that it *could* select a random user that logged into the dashboard and ensure that token has that permission to merge it. I do not see why the dashboard login cant create PAT's with that permission in that case then for free plan users and the users on the paid plans can tell mergify which specific PAT to use (Note: PAT = Personal Access Token).

**Comment by sileht** [comment]
Everything is technically possible. But I'm unsure we want to bypass the GitHub Security measure on this.

**Comment by AraHaan** [comment]
TBH While it is an github security measure, some people want their github actions to automatically get updated (and merged) only if the update works properly and passes the CI (just like any other dependabot updates).

**Comment by sileht** [comment]
Yeah, I agree with your use-case for GitHub workflow that uses only `on/pull_request` events. Even at Mergify we have some workflows we would like to update automatically. But GitHub Workflows are not just pull request centric, they offer much more.

I'm not saying we will never do it. It's just a responsibility we don't want to take yet :)

**Comment by sileht** [comment]
If new permission are accepted, Mergify is now able to merge changed workflow.
