### ISSUE TITLE
Smart strict mode not working as expected

### ISSUE THREAD

**Issue by edahlseng** [Mergifyio/mergify-engine#281]
I've run into a situation where smart strict mode is not working as expected. We have a handful of PR's up on a repository, several of which currently either have failing status checks or haven't been approved yet. There is a PR further up on the list, however, which has passed all of the status checks and has been approved. Nevertheless, Mergify just says `In Progress — Base branch will be updated soon`, but never actually updates the PR.

**Comment by jd** [comment]
@edahlseng That requires probably more debugging. Can you reach support@mergify.io with your PR number so it can be digged into?

**Comment by edahlseng** [comment]
@jd I'll see what I can do. We rarely have PR's that can stay up for long, so we may have to create a test case on a different repo.

**Comment by sileht** [comment]
I have looked at the strict workflow backlog yesterday and found a couple of issue. Fixes have been merged too. Now the backlog is entirely proceed. So you may not be able to reproduce it.

**Comment by jd** [comment]
That sounds great. I'm gonna close this but feel free to reopen @edahlseng if you spot this again.

**Comment by edahlseng** [comment]
Awesome to hear!
