### ISSUE TITLE
Comment action

### ISSUE THREAD

**Issue by edahlseng** [Mergifyio/mergify-engine#286]
The use case that I'm running into: We use both dependabot and mergify on a repo. With the `smart` strict mode, Mergify does a great job of updating PRs in order so that our CI server isn't hammered. Nevertheless, if Mergify updates dependabot PR's, then dependabot will stop rebasing them. This is particularly unfortunate because the changes that dependabot makes often requires more customized logic to update beyond the Mergify update process (to account for conflicts within a `package-lock.json` file, for example). Conversely, dependabot can be configured to rebase it's own PRs, but it will rebase all of them at once. With multiple PRs this can easily overload our CI server. Luckily, though, dependabot PR's can be rebased one at a time by creating a comment with the content's "@dependabot rebase," which leads me to the request...

If there was a boolean "next PR" condition that represented the next PR that matches all conditions, and a "comment" action, then Mergify could be used to control dependabot, allowing PRs to be updated in order.

This is the best solution I've come up with so far... If you have any better solutions to this issue, please let me know!

**Comment by edahlseng** [comment]
After thinking on this some more, I think I've found a better solution: Dependabot's rebase technique is really only needed when there are merge conflicts. So a combination of a condition that checks to see if there are conflicts, and a comment action for that case would be enough for this to be a pretty fluid workflow with Mergify (and a little bit simpler than what I outlined above!).

**Comment by jd** [comment]
I think that the potential issue with the `comment` action is that it could be triggered too often, or Mergify would have to track the fact that it already has commented a PR. Which is not that easy.

**Comment by mvines** [comment]
+1 for adding  a comment action

**Comment by jd** [comment]
We know have this, closing.
