### ISSUE TITLE
Mergify doesn't always notice when my checks pass

### ISSUE THREAD

**Issue by bowlofeggs** [Mergifyio/mergify-engine#287]
Greetings!

I've noticed that Mergify sometimes doesn't notice when checks pass and gets stuck in a state of saying it's waiting for them. Here's an example PR that I can keep open for a few days:

https://github.com/fedora-infra/bodhi/pull/2687

Note that all the tests have finished and reported passed, but Mergify says it's still waiting on a handfull of them, such as "f27-python2-unit":

https://github.com/fedora-infra/bodhi/pull/2687/checks?check_run_id=26700761

For reference, this is my current ```.mergify.yml```:

https://github.com/fedora-infra/bodhi/blob/d5fc35e80fdcbbf13755578f2723b96c6440b995/.mergify.yml

**Comment by sileht** [comment]
Hum, looks like the `GET /repos/:owner/:repo/commits/:ref/status` API return only 30 statuses...
I will replace it by `GET /repos/:owner/:repo/commits/:ref/statuses`.
