### ISSUE TITLE
Add a method to rebase/merge master in a PR

### ISSUE THREAD

**Issue by jd** [Mergifyio/mergify-engine#291]
It can happen that a pull request does not pass the CI because the master branch is broken. Then, when it's fixed, in order to have the CI passing on a PR, the pull request needs to be rebased on master (or master merged in the PR).

When using the GitHub branch protection, there's a button to do that in the UI. But when not, there's no way to do it.

It'd be nice to have a way to force Mergify to rebase/update the PR on demand.

**Comment by sileht** [comment]
I see something like:

@mergify[bot] rebase

**Comment by jd** [comment]
This is now implemented with the rebase command: https://doc.mergify.io/commands.html#rebase
