### ISSUE TITLE
Config Editor does not signoff commits.

### ISSUE THREAD

**Issue by AraHaan** [Mergifyio/mergify-engine#2946]
## Expected Behavior
The Configuration Editor should sign off commits created by it.

## Actual Behavior
The commits are not signed off.

## Steps to Reproduce the Problem

  1. Open the configuration editor.
  2. Select a repository.
  3. Edit it's configuration and press to open a pull request for the changes.

## Specifications

  - Pull Request URL: https://github.com/Elskom/Sdk/pull/237 (I had to run ``git commit --amend --signoff`` to fix this PR)
  - Mergify Config URL: https://github.com/Elskom/Sdk/blob/main/.github/mergify.yml

**Comment by jd** [comment]
We have added this feature. :)

**Comment by AraHaan** [comment]
oh, I do not see it commited to main on this repository nor did I get the commit like that in that PR (I had to manually add the signoff).

**Comment by sileht** [comment]
The pull request is created by the dashboard/website directly, the code is not public. You have to reload the configuration editor to get the new version.

**Comment by AraHaan** [comment]
Ah I see thanks.
