### ISSUE TITLE
Mergify bot commenting to non relevant comments (no mergify mention)

### ISSUE THREAD

**Issue by 0xc0170** [Mergifyio/mergify-engine#3068]
## Expected Behavior

No comments if we do not use real Mergify name

## Actual Behavior

I've noticed already two unrelated Mergify comments on PRs when I commented today, Mergify responded even though it was not asked to do any action (no command given). Has anything changed today? We haven't changed our Mergify config in the last two weeks.

See https://github.com/ARMmbed/mbed-os/pull/15022#issuecomment-905390905 or https://github.com/ARMmbed/mbed-os/pull/15020#issuecomment-905391271

## Steps to Reproduce the Problem

Any comment to our PRs will result in Mergify reacting

## Specifications

  - Pull Request URL: https://github.com/ARMmbed/mbed-os/pull/15020#issuecomment-905391271
  - Mergify Config URL: https://github.com/ARMmbed/mbed-os/blob/master/.mergify.yml

**Comment by jd** [comment]
Hi!

This was a bug that happened during ~an hour. We pushed a fix (and a test) so it does not happen again.

Thanks for the report!
