### ISSUE TITLE
Ability to backport a pull request when workflow directory changed

### ISSUE THREAD

**Issue by leseb** [Mergifyio/mergify-engine#3109]
## Expected Behavior

Mergify creates a backport PR even if the code from the original PR changes a file in the `.github/workflows` directory. Maybe a custom flag could override this default behavior?

## Actual Behavior

Mergify rule fails with `GitHub App like Mergify are not allowed to create pull request where .github/workflows is changed.`.

## Steps to Reproduce the Problem

  1. Open a PR that touches files in `.github/workflows`
  2. Add a backport label
  3. Merge the PR
  4. Backport is not created

**Comment by sileht** [comment]
If new permission are accepted, Mergify is now able to backport changed workflow.
