### ISSUE TITLE
Enhance backport pull requests on conflicts

### ISSUE THREAD

**Issue by jd** [Mergifyio/mergify-engine#336]
Some people use backport automerge, but there's a drawback.

If a backport conflicts, Mergify has no way to identify it (except maybe a regexp on the `body`). It'd be good if the backport action could be customizable to have specific action maybe when there's a conflict (like do nothing, label the created pull request, etc).

**Comment by dsavineau** [comment]
We just ran into this kind of situation. The backport has been automatically created and shows a conflict.
For some obscur reasons our CI didn't trigger all tests so all checks passed.
Then the backport PR was merged with the conflict.

https://github.com/ceph/ceph-ansible/pull/3916

**Comment by jd** [comment]
Well, in that case, the real issue is your CI. 😅

**Comment by dsavineau** [comment]
Sure but in the case there's no CI the issue will still exist

**Comment by mvines** [comment]
👍 on this feature.  On a backport merge conflict, it would be so nice if Mergify could take some action such as setting a label ("backport-failed" or something).

**Comment by jd** [comment]
Mergify will not create backports for conflicting PR anymore. That means there won't be any chance you automatically merge a problematic backport in your branch.

You can force back the old behavior by using the `ignore_conflicts` option: https://doc.mergify.io/actions.html#backport
