### ISSUE TITLE
Add documentation (example) when author is team

### ISSUE THREAD

**Issue by ghtmtt** [Mergifyio/mergify-engine#337]
Hi guys,

I have some troubles when the `author` condition is a team/organization rather than a single person. Do you mind to add a comment to this issue on how to set this condition? I'll make a PR on the doc side with a working example.

Thanks for mergify :)

**Comment by jd** [comment]
What's your problem exactly?

You can write something like `author=@myorg/myteam` to check that the author is the member of this team.

**Comment by ghtmtt** [comment]
seems not working. e.g. I'm an editor (=team) of faunalia (=organization). But still if I add `author = @faunalia/editor` the condition is not taken into account

**Comment by jd** [comment]
@ghtmtt is your repo public? If so having an example of what's not working would help. Otherwise feel free to send a mail to support@mergify.io so we can look into it and maybe debug!

**Comment by ghtmtt** [comment]
yep, it is just a test repo without any sense, just testing :)

https://github.com/ghtmtt/merge-test

**Comment by jd** [comment]
@ghtmtt I don't see any pull request with that issue, would you mind pointing me at one? :)

**Comment by jd** [comment]
Hm, it's likely that your user @ghtmtt cannot access the member list of `@faunalia/editors` so Mergify cannot match anything here.
@sileht WDYT?

**Comment by ghtmtt** [comment]
mmm OK. Because what I'm trying to set up are conditions like:

1. the author of the PR has writing rights on that repo (AKA is member of the team of the organization), then automatically merge it
2. if the author has not writing rights than don't merge the PR and close it

If you have smarter ideas of this workflow, more than welcome :)

**Comment by sileht** [comment]
I looks at the log and I confirm that Mergify cannot access the @faunalio organization on behalf of @ghtmtt .
Github returns `403 Resource not accessible by integration`

**Comment by sileht** [comment]
To be clearer, even if used @ghtmtt have permissions to looks/edit teams of @faunalio organization. Github does not allow any application to looks to organization team on behalf of user.

So, only Github application installed on @faunalio organization will be able to looks at @faunalio teams.

**Comment by ghtmtt** [comment]
Hi, thanks for the answer. So basically the PR has to be made in a repository owned by the organization?

I'll make some tests and keep you updated
