### ISSUE TITLE
Add options to set committer

### ISSUE THREAD

**Issue by foriequal0** [Mergifyio/mergify-engine#339]
I think it would be nice to have options to set author/committer per repository like:
```yaml
actions:
  merge:
    committer: Our Friendly Merge Bot <email-of@some-company.com>
```
We use CLAHub. It makes sure all committers should sign to Contributor License Agreements. Mergify[bot] is a committer to all merge commits, but it doesn't have an actual Github account so it couldn't sign to it. This causes the master branch's checks to fail. A red 'x' appears to the right of our repository name. We could wait for CLAHub to add a whitelist feature, but it doesn't seem to be maintained. (Latest commit is dated at 2 years ago)
<img width="625" alt="image" src="https://user-images.githubusercontent.com/5465658/51449515-bd89a280-1d6f-11e9-9806-f1649f46a98e.png">
There is also a problem that Travis can not filter using `sender`. We wanted to skip a check for a commit that made by Mergify[bot] on master since we do strict merge, and prohibit direct push to merge. All merge commit on master made by Mergify[bot] is identical to HEAD of Pull Request just before merge and have already been verified. But we couldn't do that. I think the 'sender' reported by Travis should be the actual Github login ID.
https://docs.travis-ci.com/user/conditions-v1#integration

Adding options to customize committer (by e-mail? SSH Key? Github OAuth?) per repository would resolve these problems. 
Thank you.

**Comment by philmd** [comment]
> Not all commits created on behalf of Mergify-bot are done by Mergify itself.
> 
> For example , in strict mode, I think we could set the commiter of the merge commit or rebased commits.
> but when we merge the pull request with `method=merge` or `method=rebase`, the merge commit is created by Github and we cannot edit the commiter.

Currently in these modes the GIT_COMMITTER_NAME and GIT_COMMITTER_EMAIL are rewritten as `mergify[bot] <mergify[bot]@users.noreply.github.com>`.
So the committer information is lost.
It should be possible to keep the committer authorship, but add `Co-authored-by: mergify[bot] <mergify[bot]@users.noreply.github.com>`.

For more information on the `Co-authored-by` tag, see:
https://git.wiki.kernel.org/index.php/CommitMessageConventions
https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors#required-co-author-information

**Comment by sileht** [comment]
`queue`, `merge` and `rebase` actions have `bot_account`, `update_bot_account`, `merge_bot_account` attributes that can be used to override these informations.
