### ISSUE TITLE
Stop the PR updates that has changed to not mergeable.

### ISSUE THREAD

**Issue by foriequal0** [Mergifyio/mergify-engine#340]
We use strict updates, so once the PR rules are met, it is updated until it got merged.
But sometimes the rule is broken by such as new commits, new reviewers, new reviews, `do-not-merge` label, `[WIP]` prefix, etc. Then it shouldn't be updated anymore.
But our PR is updated constantly after I pushed an additional commit and my reviewer added another reviewer to the PR waiting to be merged.
<img width="707" alt="image" src="https://user-images.githubusercontent.com/5465658/51585626-6f1a0680-1f1d-11e9-9ceb-1c4533683495.png">

The document describes the update mechanism as follows.
```
Mergify will queue the mergeable pull requests and update them one at a time serially.
```
I think mergify should dequeue the PRs that are not mergeable anymore, too.

**Comment by sileht** [comment]
Can you send the url of the PR ? If this is a private repository you can sent it to support@mergify.io.

**Comment by foriequal0** [comment]
Here's the PR: https://github.com/CodeChain-io/codechain/pull/1142

**Comment by sileht** [comment]
This issue have been fixed some time ago and should not occur anymore.
