### ISSUE TITLE
Add option to rebase PR without merging

### ISSUE THREAD

**Issue by pascalberger** [Mergifyio/mergify-engine#350]
It would be nice to have the option to automatically rebase source branch on target branch (if possible) but without automatically merging the PR afterwards

**Comment by beatngu13** [comment]
I would welcome this feature too. This would be helpful to keep open PRs (that haven't been reviewed so far) up-to-date.

**Comment by jd** [comment]
This is doable with the `rebase` command or action:

- https://doc.mergify.io/commands.html#rebase
- https://doc.mergify.io/actions.html#rebase

**Comment by beatngu13** [comment]
Oh, RTFM I guess. 🙈 Thx for the update!
