### ISSUE TITLE
Allow to ignorecase for regular expression (and maybe other regex flags?)

### ISSUE THREAD

**Issue by sileht** [Mergifyio/mergify-engine#358]
We currently can't ignore the case for regular expression. We should find a way to allow it.

**Comment by Lemmingh** [comment]
Hi,

What about adding a note to documentation saying that
Mergify uses Python regular expression with [search()](https://docs.python.org/library/re.html#re.search).
Then users can include `(?aiLmsux)` flags in regular expression confidently.
