### ISSUE TITLE
Backporting picking more commits then expected

### ISSUE THREAD

**Issue by renatocaval** [Mergifyio/mergify-engine#359]
We recently enabled backporting in our projects and got a two cases in which mergify is picking more commits than expected.

For example, this backport PR has tree commits:
https://github.com/playframework/playframework/pull/9136/commits

The first commit, "Fix mergify config (#9126)", was never intended to be backported.

The second commit, "Synchronize evolutions code", has it's own backport PR. 
https://github.com/playframework/playframework/pull/9127

The last commit, "Configure travis to build only stable branches and tags" is the one related with https://github.com/playframework/playframework/pull/9132 and is correct.

The same happened on that other PR:
https://github.com/playframework/playframework/pull/9120/commits

The first commit, "akka-http 10.1.8", was already backported and was not expected to be part of this backporting.

Before enabling it in our branches, I have done some tests on a test project and everything seemed to work fine. The tests were done a few months ago, so I suspect that this is a regression.

**Comment by sileht** [comment]
I have done some investigation. And found that the "squash"merge method + backports doesn't work well and have never worked if the PR have more than one commit.

Currently the backport procedure run is the one associated with the "rebase" merge method. At first glance, there is no Github API to easly identify which method have been used. We current have some heuristics for "rebase" and "merge" method, but nothing for "squash".

We need to find something differentiate  "rebase", from "squash" method.

**Comment by mkurz** [comment]
Maybe parse the commit message of the squashed commit? E.g. if you look at https://github.com/playframework/playframework/commit/e24b0d04b9fe749ccf6ef2741cbf7f84051d752c

```
title (#9110)

* commit 1

* commit 2

* commit n
```

So if after the title there is a `(#<number>)` pattern and a list of strings, separated by blank lines and starting with a `*` it seems to be a squashed commit?

**Comment by renatocaval** [comment]
I didn't look into how it's effectively done by Mergify, but shouldn't that be a simple `git cherry-pick` command?

If I do a `cherry-pick`, it never matters if it was a merger or a squash. It always works and it has the added value that the original commit message is reserved.

**Comment by sileht** [comment]
Mergify `cherry-pick` commits of the pull request, but not all commits of a pull request have to be cherry-picked.

For example commits that are 'Merge from "master" into "my-pr-branch"' must not be backported.

Also we can't rely on commit message as it can be customised when the pull request is merged manually.

**Comment by howardjohn** [comment]
Is there any ongoing work on this area?

**Comment by sileht** [comment]
I have an idea with the new API introduced recently: https://developer.github.com/changes/2019-04-11-pulls-branches-for-commit/

That should be ready soon.

**Comment by howardjohn** [comment]
Great to see this fixed! how does the release process work for mergify, will this already take effect?

**Comment by jd** [comment]
@howardjohn yes, we use continuous deployment.
