### ISSUE TITLE
Grant Mergify access to protected branches on GitHub

### ISSUE THREAD

**Issue by cipher1024** [Mergifyio/mergify-engine#361]
My master branch is only accessible by the a small group of maintainers. This seems to block mergify from accepting pull requests. How can I give mergify rights to my master branch?

**Comment by jd** [comment]
Do you have an error message from Mergify?
Feel free to reach support@mergify.io with your PR number (if it's private) so we can investigate.

**Comment by cipher1024** [comment]
This PR is the first that I was able to merge with mergify: https://github.com/leanprover-community/mathlib/pull/831. It happened right after I removed branch protection.

I just put back branch protection and this one should be failing soon:

**Comment by cipher1024** [comment]
https://github.com/leanprover-community/mathlib/pull/873

**Comment by jd** [comment]
Right, I did not understand you were using branch protections to do that. As far as I know, you can't use that — that's a GitHub limitation.

**Comment by cipher1024** [comment]
Sorry for the confusion

**Comment by cipher1024** [comment]
Here is the error that I get. Is this informative enough?

![Screen Shot 2019-04-04 at 4 40 09 PM](https://user-images.githubusercontent.com/71008/55587065-84b76380-56f8-11e9-93db-2aa4c7678213.png)

**Comment by cipher1024** [comment]
I mean, I don't want to merge that PR if it's going to remove the information that you guys need to fix the issue

**Comment by jd** [comment]
I'll let @sileht comment but I don't think we can fix this. If there's no way to add an application in a team or to give it permission in the branch protection settings, there's nothing on our side we can do AFAICT.

**Comment by cipher1024** [comment]
Possible work around: require a review from the file owners before merging and make the team of maintainers the owner of all files

**Comment by sileht** [comment]
The branch protection setting "Restrict who can push to matching branches" does not allow to put GithubApp. This is a Github Limitation. What ever you do, if this settings is ticked, Mergify can't work.

**Comment by eli-jordan** [comment]
What about using the api equivalent of clicking the “merge” button in the PR? This doesn’t require push permission

**Comment by sileht** [comment]
We use this API

**Comment by eli-jordan** [comment]
Ok. I assumed that wasn't used because I have used [bulldozer](https://github.com/palantir/bulldozer) in the past, and it works fine with protected branches.

**Comment by sileht** [comment]
Bulldozer needs to hardcore an usertoken : https://github.com/palantir/bulldozer/blob/develop/README.md#can-bulldozer-work-with-push-restrictions-on-branches

**Comment by eli-jordan** [comment]
Ah ok, that makes sense. I guess thats a bit easier with a self hosted bot :)

**Comment by jd** [comment]
This is now possible since GitHub implemented the feature:
https://developer.github.com/changes/2019-09-05-apps-protected-branches-api/

Nothing to do on Mergify's side.
