### ISSUE TITLE
Merged PR despite lack of completion of GitHub branch protections

### ISSUE THREAD

**Issue by lorengordon** [Mergifyio/mergify-engine#3661]
Not really sure how this was possible, as I figure GitHub branch protection ought to have prevented it, but here we are.

## Expected Behavior

Mergify should not have merged the PR because GitHub branch protections were not met.

## Actual Behavior

Mergify merged the PR anyway.

## Steps to Reproduce the Problem

Really not sure!

## Specifications

  - Pull Request URL: https://github.com/plus3it/terraform-aws-org-new-account-support-case/pull/159
  - Mergify Config URL: https://github.com/plus3it/terraform-aws-org-new-account-support-case/blob/master/.mergify.yml

**Comment by sileht** [comment]
Did you paste the correct pull request URL? this one is still open.

**Comment by lorengordon** [comment]
Omg, I blame that I just woke up. I saw the approval email and typically it merges immediately after approval, so I leapt to the wrong conclusion.
