### ISSUE TITLE
Allow to customize automatic backports

### ISSUE THREAD

**Issue by sileht** [Mergifyio/mergify-engine#37]
We should allow user to configure associated labels and title.

**Comment by renatocaval** [comment]
We are especially interested in the possibility of having the title configurable. 

But not only for backports. Also for automatic merges. 

The problem that we see is that GitHub UI treats merges different from squashes. 

If it's a squash, by default, GitHub uses the title of the PR + (#num):

```
Added support for feature X (#10) 
``` 

while a merge, will produce something similar to:

```
Merge pull request #11 from renatocaval/to-merge
```

The backport in mergify, follows the later:

```
Merge pull request #12 from renatocaval/mergify/bp/1.0.x/pr-10
```

It will be great if we could configure it to produce:

* Added support for feature X (#10) - for squash
* Added support for feature X (#10) - for merge
* Added support for feature X (#10 backported) - for backport

Or a variation of this, eg:

* Added support for feature X (#10 squashed)
* Added support for feature X (#10 merged)
* Added support for feature X (#10 backported)

Where `Added support for feature X` is the original title of the PR.

WDYT?

**Comment by ignasi35** [comment]
See https://github.com/Mergifyio/mergify-engine/pull/392

**Comment by leseb** [comment]
Being able to also customize the PR body would be nice. Many CIs are parsing the content and if they find something like `[test foo]`, that would run the `foo` pipeline instead. We could do that we labels, if the original PR has a given label then we match this as a message in backport PR.

Thanks!

**Comment by jd** [comment]
@renatocaval you can now specify the commit message from the body https://doc.mergify.io/actions.html#defining-the-commit-message or from the PR itself with `commit_message: title+body` so I think everything's covered in your case?

**Comment by jd** [comment]
> Being able to also customize the PR body would be nice. Many CIs are parsing the content and if they find something like [test foo], that would run the foo pipeline instead. We could do that we labels, if the original PR has a given label then we match this as a message in backport PR.

I've never seen a CI parsing the body for anything. Do you have a live example of that?

I imagine we could an option to duplicate (some) of the labels too.

**Comment by leseb** [comment]
> > Being able to also customize the PR body would be nice. Many CIs are parsing the content and if they find something like [test foo], that would run the foo pipeline instead. We could do that we labels, if the original PR has a given label then we match this as a message in backport PR.
> 
> @leseb I've never seen a CI parsing the body for anything. Do you have a live example of that?
> 
> I imagine we could an option to duplicate (some) of the labels too.

Here is a Jenkins file example parsing the body of the PR and triggering the appropriate pipeline: https://github.com/rook/rook/blob/master/Jenkinsfile#L23-L58.
Rook does that and the Ceph org a bunch too.

**Comment by leseb** [comment]
@jd I think simply re-using the initial PR content will solve my use case too :)
