### ISSUE TITLE
bug: command in code code block should not be parsed

### ISSUE THREAD

**Issue by Xuanwo** [Mergifyio/mergify-engine#3833]
## Expected Behavior

Do nothing

## Actual Behavior

Take https://github.com/Mergifyio/mergify-engine/pull/3832 for reference.

![image](https://user-images.githubusercontent.com/5351546/147345410-01a60324-09a3-4f9f-a9e9-8e28812dd98d.png)

## Steps to Reproduce the Problem

  1. Commend in PR with `@mergifyio squash`

**Comment by sileht** [comment]
This has been fixed by https://github.com/Mergifyio/mergify-engine/pull/4048
