### ISSUE TITLE
GitHub Page auto-build fails when changes merged by Mergify

### ISSUE THREAD

**Issue by joshuagl** [Mergifyio/mergify-engine#386]
The [Precaution](https://github.com/vmware/precaution) project has its documentation in the _docs/_ subdirectory and automatically publishes to GitHub Pages when the docs change, however since starting to use Mergify we noticed that our documentation wasn't being updated and GitHub reported a generic page build failure.

In vmware/precaution#205 I observed that if I manually merge a PR with docs changes the Pages are rebuilt correctly and realised this is probably Mergify related.

The GitHub Pages documentation is a bit light in places, but I infer that automatic doc builds should work when the committer is a member of the project with a verified email address (this isn't explicitly stated, but reflects what is stated for User and Organization Pages). Is the Mergify service account using a verified email address?

I'm not sure what else might be causing this to fail.

**Comment by joshuagl** [comment]
__Note__: we're not the only ones running into this issue, for example see this StackOverflow question:
https://stackoverflow.com/questions/55756906/page-build-failed-after-auto-merging-pull-request-to-github-pages-master-branc

**Comment by jd** [comment]
Mergify is [GitHub App](https://developer.github.com/apps/about-apps/) so it's a bit different — there's nothing you could call "verified email address".

Now, Mergify's engine just presses the "Merge" button on behalf of the Organization. It seems that GitHub may not run certain hooks in that case.

Even stranger, we actually use GitHub pages for https://doc.mergify.io and we never hit the issue. 🤔

**Comment by joshuagl** [comment]
We're using "master branch /docs folder" as our page's source and Pages are built automatically when the files within change, unless Mergify merges the PR.
Unfortunately GitHub isn't giving any errors beyond "Your site is having problems building: Page build failed." - is there anything we can do to better debug this issue?

Would you usually expect the mergify app to show up anywhere in the "Collaborators and teams" section of the GitHub Settings?

**Comment by jd** [comment]
I'd recommend reaching to GitHub support to understand why the page building fails. There might have clues internally on what's going on.

GitHub Apps are not listed as collaborators nor teams, they're listed in their own section in your organization in `https://github.com/organizations/<yourorg>/settings/installations` with their permissions.

**Comment by joshuagl** [comment]
I've just heard back from GitHub support. They informed me that there's a branch protection mechanism for automatic GitHub Pages builds where bot users aren't able to built GitHub pages after merging a PR. GitHub apps don't have permission to trigger builds.

GitHub support deduced that the reason the Mergify Pages build OK is because the Travis build deploys the Pages and makes requests to GitHub using a personal access token, meaning it's authenticated as a user account rather than a bot account. Whereas on Precaution we don't automate our Pages deployment beyond GitHub's feature to automatically build and deploy changes to our _docs/_ directory.

GitHub's recommendation, in order to support docs builds from bot-merged PRs, is 
> "making an authenticated API request to start a site build, using an OAuth app"

**Comment by jd** [comment]
This makes total sense, thanks @joshuagl!

We'll try to keep this open. We should take a look at how to make this kind of request on behalf of users.

**Comment by joshuagl** [comment]
Thanks @jd 

Note: we're seeing a similar thing with Issues not being closed by Mergify merged PRs, despite Fixes/Closes tags in a PR or commit message the Issue remains open when MergifyBot handles the merge.

**Comment by jd** [comment]
We've seen that as well on some account. It looks like GitHub also has some restriction on this for whatever reason 😢

**Comment by jd** [comment]
We reported this issue to GitHub who indicates that our apps need access to write permission for GitHub Pages. We've now updated the permission and it should make this works automagically.

**Comment by noelelias** [comment]
Hey @jd it's still not working for me. Is there anything I have to do?

**Comment by jd** [comment]
Hi @noelelias! No, can you provide more details about your setup and what's not working?

**Comment by noelelias** [comment]
Sure it's this OpenSource project: https://github.com/Yes-Theory/yes-theory.github.io/

I use mergify to manage who can edit which file. Currently I'm using a workaround (see GitHub actions) which works perfectly. But you can see if the user who's initiated the request isn't a member it won't start the publishing process.

My workaround is basically just an empty push from an Ubuntu docker container (here I use GitHub actions) which I send if someone else than me committed something. It's part of the project you can find it under the "actions" tab.

![Screenshot_20191208-232227~2](https://user-images.githubusercontent.com/9931929/70397384-0abb4500-1a12-11ea-9863-5ea70c9c5089.jpg)
![Screenshot_20191208-232304~2](https://user-images.githubusercontent.com/9931929/70397388-10b12600-1a12-11ea-89c5-921ac70f60ee.jpg)
![Screenshot_20191208-232346~2](https://user-images.githubusercontent.com/9931929/70397393-1c045180-1a12-11ea-9904-96c6366fdccc.jpg)
