### ISSUE TITLE
Pull request stuck in merge queue due to mergeable_state unknown

### ISSUE THREAD

**Issue by sileht** [Mergifyio/mergify-engine#397]
When pull request in merge queue raise an exception, this one is put back at the end of the queue.

But sometimes due to the famous Github bug where mergeable_state is never computed, a pull requests can stay in queue forever.

We should detect this and report that to the user.

**Comment by sileht** [comment]
Maybe when we will expose the merge queue, we can add a comment with the last failure reason.

**Comment by pocmo** [comment]
I think we ran into exactly this with our https://github.com/mozilla-mobile/fenix repository. Is there any way to resolve this manually?

**Comment by sileht** [comment]
This was an issue of the strict mode queue that has been dropped.
