### ISSUE TITLE
Issues are not getting closed on merge

### ISSUE THREAD

**Issue by jd** [Mergifyio/mergify-engine#410]
When Mergify merges pull request, it happens that the commits with `Fixes xyz` do not close the associated issues.

This seems to be a GitHub bug/limitation where they don't trigger the regular behaviour when a GitHub Application handles the merge.

**Comment by jd** [comment]
We'll work with GitHub on this and see if we can implement a work around in the meantime.

**Comment by mkarp** [comment]
Very needed indeed 🙏

**Comment by jd** [comment]
I've reported the issue to GitHub product management in the meantime.

**Comment by mvlabat** [comment]
Today I received an email that Mergify requested write access to the issues. So I assume that's the fix? :)
(I haven't got a chance to test it yet..)

**Comment by sileht** [comment]
@mvlabat yes, it is. After some help from Github we figure out we just need this permissions, nothing else. The Github post merge process uses the GithubApp permissions to do its jobs, it was closing issues on our behalf. That's why we need this permission.
