### ISSUE TITLE
Backport won't work after renaming the target branch for those Pull Requests targeting the old branch

### ISSUE THREAD

**Issue by v1v** [Mergifyio/mergify-engine#4168]
## Expected Behavior

Backport to happen

## Actual Behavior

Backport won't happen

## Steps to Reproduce the Problem

  1. Merge a Pull Request
  2. Rename the target branch
  3. GitHub command with `Mergifyio backport <branch>`

## Specifications

  - Pull Request URL:  https://github.com/elastic/beats/pull/29695
  - Mergify Config URL: https://github.com/elastic/beats/blob/main/.mergify.yml
  - Error -> https://github.com/elastic/beats/pull/29695#issuecomment-1048731854

Likely this is a corner case.

**Comment by sileht** [comment]
Not sure we can do anything about this, the pull request still references the old target branch even if it does not exist. There is no way for Mergify to known/understand the branch has been renamed or deleted.

**Comment by v1v** [comment]
I understand this is a kind of corner case, :(  Thanks @sileht , I'll close this issue now
