### ISSUE TITLE
Don't follow repositories without a .mergify.yml

### ISSUE THREAD

**Issue by aspiwack** [Mergifyio/mergify-engine#438]
As an Github Org admin, I would like to enable mergify for all the Org member to use when they need it.

As it stands, this is not possible: mergify will try to take control of merging in every repository in the branch. In repositories without a .mergify.yml, mergify, it will yield Red checks on all PRs.

This seem to imply that either every repository in the Org use mergify, or admins need to whitelist individual repositories every time a repository wants to use mergify.

As a way to achieve the desired result: everybody can use it if they want, it would be good if mergify would not try to act on repositories which haven't configured a `.mergify.yml`. Then, opting in, would consist in adding a `.mergify.yml` to a repo.

**Comment by mariusvniekerk** [comment]
https://github.com/conda-forge is also interested in using mergify.  We have ~7000 repos in our org so we would need something like this.
