### ISSUE TITLE
Don't try to merge draft pull requests

### ISSUE THREAD

**Issue by alecmocatta** [Mergifyio/mergify-engine#456]
GitHub introduced the [draft pull requests feature](https://github.blog/2019-02-14-introducing-draft-pull-requests/) earlier this year.

Mergify currently tries to merge draft pull requests, resulting in the failure:

```
Repository settings are blocking automatic merging

GitHub error message: Pull Request is still a draft
```

**Comment by beatngu13** [comment]
It would be great if one could specify this as a condition. In our case, we also don't want to perform e.g. rebase when the given PR is a draft.
