### ISSUE TITLE
Control over squash-merge commit message

### ISSUE THREAD

**Issue by NGL321** [Mergifyio/mergify-engine#463]
When executing a squash-merge, mergify uses the title/message from the first commit. 

This does not make sense in situations where Conventional Commits are used, or any time a repo owner wants squashed merges to use the PR title as the commit title (Github standard).

**Comment by athar1005** [comment]
Actually I think this behavior is Github specific. When there are multiple commits in a branch Github uses PR title as message while squashing. But if there is just a single commit then the message added on squash is the same as that of single commit.

If mergify can provide a way to change this message/set it equal to PR title, that would be a nice feature to have.

**Comment by rix0rrr** [comment]
I would like the commit line equal to PR title (GitHub already does this), but more importantly the commit BODY equal to the PR message body. 

Right now if the PR is not resolved with one commit and needs a couple of rounds of review, the commit message will look like:

```
feat(thing): the feature

* feat(thing): the feature
* Fix tests
* Addressed feedback
* Oops
* Addressed review feedback
```

Which is not helpful to anyone. The only way to make sure Mergify uses a meaningful commit message is to amend-commit and force-push, which destroys review history.

It would be great if GitHub would fix this, but until they do Mergify would be a great candidate to fix this bad experience.

**Comment by sileht** [comment]
It's now possible to set the PR merge/squash message: https://doc.mergify.io/actions.html#merge

> When a pull request is merged using the squash or merge method, Mergify uses the default commit message provided by GitHub. You can override the commit message by adding a section in the pull request body. The section must start with the Markdown title “Commit Message” and contain the actual commit message. For example:


```
## Commit Message
My wanted commit title

The whole commit message finishes at the end of the pull request body or
before a new Markdown title.
```

**Comment by mvillafuertem** [comment]
> It's now possible to set the PR merge/squash message: https://doc.mergify.io/actions.html#merge
> 
> > When a pull request is merged using the squash or merge method, Mergify uses the default commit message provided by GitHub. You can override the commit message by adding a section in the pull request body. The section must start with the Markdown title “Commit Message” and contain the actual commit message. For example:
> 
> ```
> ## Commit Message
> My wanted commit title
> 
> The whole commit message finishes at the end of the pull request body or
> before a new Markdown title.
> ```

@sileht How can I set the message using template? Any example of this? Thanks

**Comment by sileht** [comment]
The message has to be written in the pull request description in the format described here: https://docs.mergify.io/actions/merge.html#commit-message

**Comment by mvillafuertem** [comment]
How can I specify only get the last commit and not add the others? For instance.

Now I get this 
```
feat(thing): the feature

* feat(thing): the feature
* Fix tests
* Addressed feedback
* Oops
* Addressed review feedback
```

But I only want 
```
feat(thing): the feature
```

**Comment by jd** [comment]
You can't do that currently. This is how GitHub generates the squash commit message.

Feel free to open a new issue if you want to be able to use a different way!
