### ISSUE TITLE
Closing issues with keywords doesn't work

### ISSUE THREAD

**Issue by mboes** [Mergifyio/mergify-engine#466]
GitHub supports closing issues [using keywords in PR's and commits](https://help.github.com/en/articles/closing-issues-using-keywords). This has stopped working for us since we started using Mergify. If Mergify merges the PR, then any issues mentioned using keywords in either the PR message or any commit message will _not_ close as part of the merge.

Related: https://github.community/t5/GitHub-API-Development-and/Pull-requests-merged-through-the-API-are-not-auto-closing-issues/td-p/25700. This could be due to Mergify not requesting enough permissions.

**Comment by jd** [comment]
This has been resolved a few months ago. Can you check that Mergify had the right to write to issues?
We updated the permission of the app a few weeks ago but if you did not accept the new permissions, it won't work.

**Comment by jd** [comment]
See #410 for details.

**Comment by mboes** [comment]
Ah indeed. Just this morning an issue got merged in that autoclosed fine. The issues I was looking were from early June. Will let you know if this happens again, but closing for now, thanks!
