### ISSUE TITLE
GitHub workflow matrix not matching

### ISSUE THREAD

**Issue by thislooksfun** [Mergifyio/mergify-engine#486]
My PR over at https://github.com/thislooksfun/earthdawn/pull/34 is not being automatically merged even though it should be because Mergify isn't seeing the `Unit Tests / build (10.x) (push)` and `Unit Tests / build (12.x) (push)` checks as being passed, even though they are. Any idea what I'm missing to get this to work?

**Comment by sileht** [comment]
Looks like Github is tricky people with their action names.
Github API returns only `"name": "build (10.x)",`, neither check-suite or check-runs contains `Unit Tests` and `(push)`.

So to workaround your issue just use "build (10.x)" is your `.mergify.yml`, I will add a note into the documentation. And we will see later if we have something better for this new kind of checks.

**Comment by sileht** [comment]
There is many other issues with what Github API returns for Github Actions. I have open a support ticket. We will see.

**Comment by kylemh** [comment]
Found this really helpful! Consider adding this to documentation under "Conditions" - even if it's only temporary!

**Comment by allez-allez-allez** [comment]
Been looking for this. Thanks for pointing it out.

**Comment by sileht** [comment]
This may no longer work as Github now put a random uuid as name for GH Action Check name when you retrieve them via API.

**Comment by kylemh** [comment]
Still working for me 🤷‍♂

**Comment by jd** [comment]
> This may no longer work as Github now put a random uuid as name for GH Action Check name when you retrieve them via API.

That only happened for a few hours, they reverted this. 🤷‍♂
