### ISSUE TITLE
Add support for GitHub required checks

### ISSUE THREAD

**Issue by thislooksfun** [Mergifyio/mergify-engine#487]
GitHub has built-in support to mark certain checks as required, is there a way to tell Mergify to wait for those required checks, or do I have to write them all out manually in the config?

**Comment by jd** [comment]
For now, you have to write them manually in the config.

**Comment by thislooksfun** [comment]
Ah, that's a shame. Oh well. Hopefully someday! 🤞

**Comment by jd** [comment]
This is now supported out of the box. If you have branch protection enabled, Mergify will respect this and not try to merge if your mandatory checks do not pass.
