### ISSUE TITLE
length of value must be at most 100 for dictionary value @ pull_request_rules → item 0 → conditions

### ISSUE THREAD

**Issue by hongbo-miao** [Mergifyio/mergify-engine#5106]
## Behavior

My Mergify config has not been changed for a while. But today I started to get this error in Mergify:

> The current Mergify configuration is invalid
> length of value must be at most 100 for dictionary value @ pull_request_rules → item 0 → conditions

Any ideas? Thanks! ☺️

## Specifications

  - Pull Request URL: https://github.com/hongbo-miao/hongbomiao.com/pull/13811/checks?check_run_id=20403682768
  - Mergify Config URL: https://github.com/hongbo-miao/hongbomiao.com/blob/main/.mergify.yml

**Comment by hongbo-miao** [comment]
I figured out, it means conditions in my Mergify config cannot have over 100 elements.
[My repo](https://github.com/hongbo-miao/hongbomiao.com) is open source and kind of large having tons of tests, Mergify works well before, is this a new limit added today?
Is it possible to increase it? Thanks! :smiley:

**Comment by sileht** [comment]
Sure, we increased the limit to 500, we just don’t want it to be infinite. The change should land in production soon

**Comment by hongbo-miao** [comment]
Thanks @sileht for helping increase, it works well now! ☀️
