### ISSUE TITLE
Approval loop on closed PRs

### ISSUE THREAD

**Issue by lorengordon** [Mergifyio/mergify-engine#5110]
## Expected Behavior

No approval action on closed PRs.

## Actual Behavior

Mergify is repeatedly marking closed PRs as approved. Several of our projects are impacted. The configs had been working fine for over a year. Issue appears to have started within the last few days. 

## Steps to Reproduce the Problem

Not super sure on this, it may be some interaction between dependabot and mergify?

  1. Dependabot closes a PR
  2. Mergify begins some approval doom-loop

## Specifications

  - Pull Request URL: https://github.com/plus3it/terraform-aws-org-new-account-delete-default-vpcs/pull/394
  - Mergify Config URL: https://github.com/plus3it/terraform-aws-org-new-account-delete-default-vpcs/blob/main/.mergify.yml

**Comment by Greesb** [comment]
Hello,

We deployed a fix that should prevent this from happening again.
Apologies for the trouble.

**Comment by lorengordon** [comment]
Thanks @Greesb !
