### ISSUE TITLE
Pull requests are ignored

### ISSUE THREAD

**Issue by remal** [Mergifyio/mergify-engine#5128]
## Expected Behavior
Mergify processes PRs and adds a check.

## Actual Behavior
Mergify completely ignores some PRs.

## Steps to Reproduce the Problem

I'm not sure if specific reproduction steps exist. Some PRs in my repositories are being ignored.

Even adding `@mergify refresh` comment doesn't help.

## Specifications

  - Pull Request URLs:
    - https://github.com/remal-github-actions/cancel-pr-actions/pull/28 (with `@mergify refresh` comment)
    - https://github.com/remal-github-actions/cancel-pr-actions/pull/30
    - https://github.com/remal-github-actions/auto-merge-pr/pull/3 (another repo with the same config)
  - Mergify Config URL: https://github.com/remal-github-actions/cancel-pr-actions/blob/main/.mergify/config.yml

**Comment by sileht** [comment]
Hi @remal, Workflow Automation is not enabled on this repository.

Workflow Automation is not enabled automatically anymore.
You to go through the dashboard and enable it on this repository.

**Comment by remal** [comment]
I enabled Workflow Automation, and it works now. Thanks! Closing the issue.
