### ISSUE TITLE
Mergify backport mangles backports by including unrelated changes

### ISSUE THREAD

**Issue by BlaineEXE** [Mergifyio/mergify-engine#5132]
## Expected Behavior

Mergify backport cherry-picks only changes from the specific commit(s) being backported.

## Actual Behavior

Mergify backport is adding more changes than just those from the commit being backported. 

Please see these 3 backport PRs mergify created that are mangled in Rook's repo:

- https://github.com/rook/rook/pull/15122
- https://github.com/rook/rook/pull/15121
- https://github.com/rook/rook/pull/15120

The first 2 are backports to different branches, from the same source PR which should update 8 files. The third is a different source PR, also updating 8 files.

The 3rd seems to be most interesting to me. It backports 2 commits. The last commit is the one that mergify is adding unexpected changes to. The first commit looks to be backported as intended.

## Steps to Reproduce the Problem

  1. Mergify backport using GH action (config link below)
  2. Observe mangled backport (links above and below)

## Specifications

  - Pull Request URL: (see below)
  - Mergify Config URL: https://github.com/rook/rook/blob/4e727f302cadde7c8503ecc067899ee51e92413e/.mergify.yml

- https://github.com/rook/rook/pull/15122
- https://github.com/rook/rook/pull/15121
- https://github.com/rook/rook/pull/15120

**Comment by BlaineEXE** [comment]
Based on the undesired changes that mergify is including, it appears that mergify is including all changes from the `master` branch in the backport instead of only the content of the commit(s) being backported.

**Comment by ankush** [comment]
We are facing a similar problem:

Examples:
- https://github.com/frappe/frappe/pull/28738
- https://github.com/frappe/erpnext/pull/44648

**Comment by BlaineEXE** [comment]
Does anyone know if it's possible to force mergify to revert back to an earlier, non-bugged version?

**Comment by ankush** [comment]
Only Mergify team can do that.

**Comment by akhilnarang** [comment]
Looks like its resolved now: https://github.com/frappe/frappe/pull/28756

Edit: was just for that PR, broken for others.

**Comment by BlaineEXE** [comment]
Still seem to be broken in Rook's repo :(

**Comment by jd** [comment]
👋 
Thanks for reporting! We'll look into this ASAP.

**Comment by DouglasBlackwood** [comment]
Hi! We released a fix for the backport action. You shouldn't reencounter the issue.
