### ISSUE TITLE
Github Actions is not recognizing validating condition

### ISSUE THREAD

**Issue by shunkakinoki** [Mergifyio/mergify-engine#523]
success validations through GitHub actions is not recognized in `status-success`

**Comment by jd** [comment]
GitHub keeps breaking their API so it's hard. Do you have a PR number to check?

**Comment by shunkakinoki** [comment]
Ys I understand, thanks for the reply
Maybe it's not of a high priority and I've found a workaround to label the pr from the github actions which then triggers the mergify merge!

**Comment by jatcwang** [comment]
Hi @jd, I have one here https://github.com/jatcwang/doobieroll/pull/3 (the "automatic merge for scala-steward pull requests affecting build.sbt" rule should trigger) but using simulation in Mergify console I see

```
#### Rule: automatic merge for scala-steward pull requests affecting build.sbt (merge)
- [X] `author=jatcwang`
- [ ] `status-success=CI / test (pull_request)`
- [X] `#files=1`
- [X] `files=build.sbt`
```

**Comment by jd** [comment]
As writte in the [documentation](https://doc.mergify.io/conditions.html#github-actions), the name should be `test`.

**Comment by jatcwang** [comment]
Ah great! Sorry I missed it when reading the docs
