### ISSUE TITLE
Document strict option

### ISSUE THREAD

**Issue by jd** [Mergifyio/mergify-engine#6]
This is not completely documented and is not a GitHub option.

@sileht I missed in the code where this is used, hint?

**Comment by sileht** [comment]
I have documented all options, mostly inspired from Github doc: https://doc.mergify.io/faq.html#what-the-default-rule-configuration

**Comment by jd** [comment]
Thanks @sileht. That need to be a somewhere else than the FAQ IMHO, but I'll work on that.

**Comment by jd** [comment]
Fixed with https://github.com/Mergifyio/mergify-engine/pull/8 then.
