### ISSUE TITLE
Duplicated comments

### ISSUE THREAD

**Issue by favoyang** [Mergifyio/mergify-engine#654]
I know it maybe a race condition that can happen from time to time. The mergify engine
got duplicated events for a PR at the same time and the comment has been sent
more than once. Just want to create an issue to track it.

i.e. the message sent four times. https://github.com/openupm/openupm/pull/24

**Comment by jd** [comment]
This is a race condition when multiple events from the same PR are handled in parallel or when GitHub API lags returning new sent data.

**Comment by favoyang** [comment]
Thanks for following up the issue. I guess maybe it could be solved by adding a layer to buffer events for a small time window to avoid duplication, because most duplicated comments are almost instantly. A common practice when handing unreliable network protocol like udp.

**Comment by jd** [comment]
We now batch events that should avoid such issues to be triggered ever again.
