### ISSUE TITLE
Required that all status checks pass before merging

### ISSUE THREAD

**Issue by azai91** [Mergifyio/mergify-engine#678]
Is there a way to set status-success condition to include all? Right now we have to explicitly list checks.

**Comment by jd** [comment]
No, because the list of "all" checks does not exist. They can vary depending on a per-PR basis.

**Comment by 0xc0170** [comment]
This was something we were looking for. As there are conditions for some checks (not always all tests run - we call it auto smart tester to choose what should be tested). The workaround (that could be in the docs) is to use for instance:

all green from jenkins ci: `- status-failure~=^jenkins-ci`

Somehow this does not work always, I am investigating why, will create a new issue if found this to be the case with more PRs, so far found one.

**Comment by jd** [comment]
@0xc0170 When a PR is created, it has 0 status check. If you write a rule with:

`- status-failure~=^jenkins-ci`

The condition will match as soon as the PR is created. So this is quite dangerous…

Any (authorized) service can 0 to an infinite number of status checks for any PR, and that might change from one PR to another.

So the list of all checks is actually never known until all CI have run… and you don't know if all CI have run or not, since they might run or might not run depending on the PR. Or they might just lag!

**Comment by 0xc0170** [comment]
> The condition will match as soon as the PR is created. So this is quite dangerous…

Something I have not seen so far. I'll keep watching this matching and might rethink this but not certain how to solve it at the moment.

> So the list of all checks is actually never known until all CI have run… and you don't know if all CI have run or not, since they might run or might not run depending on the PR. Or they might just lag!

Exactly. We just trigger CI. It knows what should run, therefore all hooks should have green status for PR to be mergable. Basically, this is green policy - all must be green. PR scope defines what should be tested. 

Let's take an example:
`jenkins-ci-test` is required for a code change but not for documentation change. There is `jenkins-ci-docs` or similar to check non-code changes. This type of rules can't be set in mergify, therefore our thinking were it is service that takes care of what should run (in our case it's CI). What is important there is a green policy - whatever runs on PR needs to be green.

This use case is more advanced, most of the time like travis or circleci has specific rules that are applied for every PR. If there is more smart testing involved, we might not have all hooks there reported per PR.

**Comment by Borda** [comment]
I am using GitHub action and I am not able to write a proper pattern role for all these tests...
This is my condition `"status-success~=^CI testing"` and this is the link to tests
https://github.com/PyTorchLightning/pytorch-lightning/actions?query=workflow%3A%22CI+testing%22

**Comment by jd** [comment]
@Borda This might help https://doc.mergify.io/conditions.html#github-actions
You should use "status-success~=^build"
Note that this condition is true as soon as **one** of the service returns success. That might not be what you want.

**Comment by Borda** [comment]
@jd so how can do that all have to be true? It sounds like a basic feature to me...
so do I have to do negation of any failed?

**Comment by jd** [comment]
The list of check running for a particular PR is completely dynamic. It can be different for any of your PR. There is no such thing as "all". There is no way to know which are going to be present for a particular PR.

Using "no status fails" is also quite dangerous: if your CI is down or lag for a few minutes/hours, then the condition will be valid…

You have to list all of them.

**Comment by Borda** [comment]
or is there a way that I want to pass all N check where I know that the total number is N=26
just feeling that writing all 26 checks which are commonly produced CI with matrix config is quite annoying...

**Comment by jd** [comment]
You can use `"#status-success=26"` as a condition.

**Comment by jd** [comment]
I wrote something in the doc https://doc.mergify.io/conditions.html#validating-all-status-check
