### ISSUE TITLE
Delete pull request base branch after merge

### ISSUE THREAD

**Issue by jd** [Mergifyio/mergify-engine#68]
This is possible right now in GitHub with a button, but having it being done automatically could be great.

Requested at https://github.com/isaacs/github/issues/1121

**Comment by mkarp** [comment]
+1 to this feature request.

**Comment by carlcheel** [comment]
+1 to this feature request.

**Comment by sileht** [comment]
this is part of engine v2: https://github.com/Mergifyio/mergify-engine/pull/223
