### ISSUE TITLE
Configuration file validation

### ISSUE THREAD

**Issue by fuzzball81** [Mergifyio/mergify-engine#69]
It would be nice to have a tool that could validate the .mergify.yml before committing it to your repository. I ran into a few syntax errors, that were caused by whitespace issues. Having a sanity check prior to committing that file would of gotten me up and running faster.

**Comment by jd** [comment]
@fuzzball81 What kind of tool would you like? A command line tool?

There's a service that validates your syntax if you send your `.mergify.yml` via a pull request, but obviously it can't work if you push to `master` direct.y

**Comment by fuzzball81** [comment]
@jd I was thinking a command line tool that is just a basic linter for the config. The other option would be some place on the website where I could paste in my config and have it checked.

I did notice, via the pull request that the syntax was checked. That is a great feature!

**Comment by sileht** [comment]
This should be done exaclty like the online converter but for validation.

**Comment by sileht** [comment]
https://github.com/Mergifyio/mergify-engine/blob/master/mergify_engine/web.py#L61-L74

**Comment by gmartinez-anchor** [comment]
There is [this entry](https://doc.mergify.io/configuration.html#validation) but it doesn't work:

```sh
$ curl -F "data=@.mergify.yml" https://gh.mergify.io/validate/ -i
HTTP/2 400
date: Mon, 18 May 2020 16:52:28 GMT
content-type: application/json
content-length: 48
set-cookie: __cfduid=d57c6da6dd26f536404af6e2ed54cb29b1589820747; expires=Wed, 17-Jun-20 16:52:27 GMT; path=/; domain=.mergify.io; HttpOnly; SameSite=Lax; Secure
via: 1.1 vegur
cf-cache-status: DYNAMIC
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 595716b9c8090672-LHR
cf-request-id: 02ca4c881f00000672a1ae6200000001

{"detail":"There was an error parsing the body"}
```

I checked that this configuration is valid on the dashboard, but ideally this would be part of the CI validation for Pull Requests.

**Comment by jd** [comment]
This should be fixed: https://github.com/Mergifyio/mergify-engine/pull/1084
