### ISSUE TITLE
Add status check for pending (status-pending)

### ISSUE THREAD

**Issue by 0xc0170** [Mergifyio/mergify-engine#707]
I initially though status = neutral is the one to be used in the case there is required status but yet not provided = pending (no success, neither failure). However, it does not work - the blog post about neutral mentions grey status. What is `neutral` ? I can't find it in https://developer.github.com/v3/repos/statuses/.

What I would like to have as condition: `status-pending` - required status has not yet been provided.

Use case: we can make actions based on not yet executed statuses (pending) - for instance CI has not yet been done (neutral status).

**Comment by jd** [comment]
See https://github.com/Mergifyio/mergify-engine/blob/master/mergify_engine/mergify_pull.py#L167-L174 for more context.
I'll @sileht comment if we want to add more details.

**Comment by 0xc0170** [comment]
> See https://github.com/Mergifyio/mergify-engine/blob/master/mergify_engine/mergify_pull.py#L167-L174 for more context.

The load can be huge to be checking for pending always. The other way around this would be "not fail neither success" would be pending.

This is how I imagine it working:

```
      - -status-success~=continuous-integration/jenkins/pr-head
      - -status-failure~=continuous-integration/jenkins/pr-head
```

**Comment by AraHaan** [comment]
Not failure, not success, and not neutral I assume is pending or skipped.

But then again I think at least a status-skipped could be added so we can filter out those for pending as well.

**Comment by AraHaan** [comment]
This is what I think so far should have statuses (``status`` and ``check`` prefixes meaning the same as they do now):

- ``check-success``/``status-success`` (the check had no issues)
- ``check-neutral``/``status-neutral`` (the gray one)
- ``check-skipped``/``status-skipped`` (for when the check is skipped)
- ``check-pending``/``status-pending`` (for pending status, and no reported but expected statuses that are part of branch protection)
- ``check-failure``/``status-failure`` (for errors, check/status timeouts, checks/statuses that says an action is required that has the red x, canceled check/status)

**Comment by AraHaan** [comment]
@jd I found 3 files, are these the only places the define the statuses?

- mergify_engine/context.py
- mergify_engine/merge_base.py
- mergify-engine/parser.py

Also I think I can jerry rig a way to do status/check pending by handling if any of the other statuses and checking if they are all false, then we should know that they *are* pending without doing an actual api check that could ratelimit.

**Comment by jd** [comment]
Don't worry about the files' years, we update them as we go. There's no need to change everything at once every year.
