### ISSUE TITLE
Old check still required by mergify

### ISSUE THREAD

**Issue by cverna** [Mergifyio/mergify-engine#754]
Hello.
We are having a weird behaviour with Mergify on the https://github.com/fedora-infra/bodhi repository.Not long ago we have updated the mergify configuration to remove some checks (f29-build, f29-integration, etc ...) (https://github.com/fedora-infra/bodhi/pull/3826), but mergify still shows these as required on the PRs

Is there anything we have done wrong ?

**Comment by jd** [comment]
I don't see those `f29` checks on e.g. https://github.com/fedora-infra/bodhi/pull/3933/checks?check_run_id=462273247

Do you have a PR we can check as example?

Mergify does not necessarily recheck all the PR when the configuration is changed; you can retrigger it with the [`refresh`](https://doc.mergify.io/commands.html#refresh) command if you need to.

**Comment by cverna** [comment]
Yes they don't appear on the mergify checks but they are on the PR view (see screenshot below). I am not 100% sure if that comes from mergify or not :smile: 

![image](https://user-images.githubusercontent.com/7237866/75758676-b71c7700-5d34-11ea-8e08-f856fa82142f.png)

**Comment by jd** [comment]
This is your GitHub branch protection settings, not Mergify:

https://help.github.com/en/enterprise/2.15/admin/developer-workflow/configuring-protected-branches-and-required-status-checks

**Comment by cverna** [comment]
> This is your GitHub branch protection settings, not Mergify:

Oh thanks and sorry for the noise :-)

> 
> https://help.github.com/en/enterprise/2.15/admin/developer-workflow/configuring-protected-branches-and-required-status-checks
