### ISSUE TITLE
Pull request titles are being dropped from commit messages.

### ISSUE THREAD

**Issue by ocharles** [Mergifyio/mergify-engine#765]
We use the `## Commit Message` feature of Mergify to set a final commit message in our PR, as we squash merge everything. However, recently commits have been losing titles:

See

![image](https://user-images.githubusercontent.com/20878/75966003-8ddd2180-5ec1-11ea-966b-9757c284abb3.png)

But here is how the PR looks:

![image](https://user-images.githubusercontent.com/20878/75966040-9d5c6a80-5ec1-11ea-905c-2b7d77ca40d5.png)

This seems to only happen if there is no blank line after `## Commit Message`. Note that this commit is correct:

![image](https://user-images.githubusercontent.com/20878/75966099-b6fdb200-5ec1-11ea-8fc0-4956f2a1d0c1.png)

![image](https://user-images.githubusercontent.com/20878/75966128-c250dd80-5ec1-11ea-9705-d55ac1548395.png)

**Comment by jd** [comment]
This is indeed a bug. I'll fix it.

**Comment by ocharles** [comment]
Is the correct/intended behavior for the GitHub title to be used in the first line of the commit message?

**Comment by ocharles** [comment]
From reading the tests, it looks like you never want to use GitHub's title. I find this a bit of a shame, as the auto-generated title with the PR number in is really useful, and otherwise my team has to duplicate the title into the `## Commit Message` area.

**Comment by jd** [comment]
Yes, that's indeed the intended behaviour for this feature.

However, we can add a different mode that implements what you want. We just have to find a good name for it.

**Comment by ocharles** [comment]
That would be very much appreciated! How about ## Commit Details?

**Comment by jd** [comment]
I'm wondering if adding support for `## Commit Message` to the `title+body` mode wouldn't be a solution?
Where `## Commit Message` would define the body, the title being taken from the pull request.

**Comment by ocharles** [comment]
I'm not quite understanding. Are you suggesting that a PR with title "Foo" (on GitHub) and description:

```markdown
## Commit Message

Hello
```

Would have a final commit message of

```
Foo

Hello
```

?

If so, yes - that's what would work best for us, and is what used to happen if you had a blank line after `## Commit Message`.

**Comment by jd** [comment]
Yes, that's my suggestion, as long as you have `commit_message: title+body` enabled on the merge action.

The idea would be that in `default`, `Commit Message` defines everything (title+body), whereas in the `title+body` mode, `Commit Message` only defines the message – not the title.

Now that I write that down, I feel it's over-complicated.

Maybe your idea of `Commit Details` is simpler as it allows you to stick with the `default` mode.  `Commit Body` might be a better name though?
