### ISSUE TITLE
Rebase and Merge fails with `No oauth valid tokens`

### ISSUE THREAD

**Issue by SteVwonder** [Mergifyio/mergify-engine#775]
Github PR check link: https://github.com/flux-framework/rfc/pull/232/checks?check_run_id=491608159

I don't see any related open issues.

Not sure how to debug further.  Any suggestions?

**Comment by jd** [comment]
It seems the token has sometimes returned as invalid by GitHub for an unknown reason. We need to dig through this more to see where the problem is between Mergify and GitHub.

**Comment by sileht** [comment]
The original bug has been fixed a while ago.

@Madhu-1 your issue was a regression fixed this morning

**Comment by Madhu-1** [comment]
@sileht Thank you it works now!!
