### ISSUE TITLE
Option to only include title in squash merge commit message

### ISSUE THREAD

**Issue by erikgrinaker** [Mergifyio/mergify-engine#787]
Mergify currently uses the default GitHub message when doing squash merges, which includes all of the branch commit messages. This can cause a lot of unnecessary noise in logs. It would be very useful with an option to only use the PR title as the squash merge message instead of the PR title and all of the branch commits.

**Comment by jd** [comment]
Hi @erikgrinaker,

Did you see https://doc.mergify.io/actions.html#commit-message-and-squash-method and does it solve your issue?

**Comment by erikgrinaker** [comment]
Hi @jd,

Yes, I’ve seen that option, but we’d prefer an option that handles this for us automatically. Manual steps like having to write specially crafted descriptions have a tendency to be forgotten, and it’s redundant anyway since the PR title has the message we want to use.

**Comment by jd** [comment]
@erikgrinaker Let me know if that works well enough for you!

**Comment by erikgrinaker** [comment]
@jd This is awesome, thanks so much for implementing this!
