### ISSUE TITLE
Invalid backport PR created

### ISSUE THREAD

**Issue by ignasi35** [Mergifyio/mergify-engine#849]
(apologies for the vague issue title)

In https://github.com/playframework/playframework/pull/10142 we tried to backport the PR from `master` to `2.8.x`. At the moment of that request, the tip of `2.8.x` was the merge commit resulting from a 1-month old merge commit (https://github.com/playframework/playframework/pull/10140).

Instead of creating a new PR with the backport of https://github.com/playframework/playframework/pull/10142 the bot commented https://github.com/playframework/playframework/pull/10142#issuecomment-602462164 

```
Command backport 2.8.x: success

    Backports have been created

    #10140 Create a unique version number when setting akka.version (bp #10083)

has been created for branch 2.8.x
```

Which indicates the bot thinks an old, already closed PR is the correct, newly-created one.

We tried multiple times but got the same response from the bot in all cases.

**Comment by jd** [comment]
Yes, we have a regression on this. We're working on a fix. Stay tuned.
