### ISSUE TITLE
Use 'rebase' rather than 'merge' as a strategy to update the PR

### ISSUE THREAD

**Issue by jd** [Mergifyio/mergify-engine#86]
The current approach in strict workflow is to merge the target branch in the PR. It'd be nice if Mergify could use a rebase operation instead to update the PR.

**Comment by branoholy** [comment]
I think it would be great if Mergify could support both strategies (merge and rebase) in the strict workflow. It should be up to the developers which strategy fits their workflow. Someone prefers merge, someone rebase.

**Comment by sileht** [comment]
We partially implement that, we have the code ready to rebase instead of merge. But it have not been enabled, because GitHub dismiss automatically all reviews, when we push the rebased branch.

So we need to wait to detect rebase and not dismiss reviews (like it does for merge), or we need to find a way to put reviews back.

**Comment by thomaseizinger** [comment]
So I did some investigation and indeed, if the above checkbox (`Dismiss stale pull request approvals when new commits are pushed`) is not checked then GitHub will *not* remove approvals if the branch is rebased.

We would really like to use mergify to implement the following workflow/process:

Mergify configuration:
- merge pull requests automatically that have a certain number of approvals
- use rebase to update the PR if it is out of date

GitHub configuration:
- don't dismiss PR reviews if new commits are pushed
- require CI to be passing
- require branch to be up-to-date

With this configuration, you are basically handing over the PR to mergify once it is approved and it will take care of updating it until it can be merged.

I took a quick look at the code and it seems that the only thing that is missing is a configuration option to instruct mergify to use rebase! It would be super cool if this feature could land soon :)

**Comment by thomaseizinger** [comment]
What is the status on this? :)
Are there plans to ship this feature?

**Comment by D4nte** [comment]
I can see that `rebase` is a valid option in the `Merge Strategy`. Does it mean it is now available?

https://doc.mergify.io/v1/configuration.html#merge-strategy
