### ISSUE TITLE
Allow to merge with 0 reviewer

### ISSUE THREAD

**Issue by jd** [Mergifyio/mergify-engine#88]
The number of reviewer required is at least 1. Some people would like to merge pull requests as soon as the CI pass, no matter what. This would be especially useful with #42.

**Comment by sileht** [comment]
Setting "required_pull_request_reviews: null" should work. We need to document that.

**Comment by tarek360** [comment]
Hi @sileht 
I tried to set `equired_pull_request_reviews: null` and mergify now isn't waiting for any reviewer approval but it didn't merge [my PR](https://github.com/tarek360/emptyapp/pull/9) although all checks have passed.
