### ISSUE TITLE
Disable auto update branch in yml

### ISSUE THREAD

**Issue by shunkakinoki** [Mergifyio/mergify-engine#890]
I was going through the documentation and didn't see an option to disable the automatic branch update. If I am mistaken, I am sorry, but is there currently a way to do this through the configuration file?

**Comment by sileht** [comment]
Mergify does not automatically does branch update. I suppose you have `strict: true` or `strict: smart` for the `merge` action.

https://doc.mergify.io/actions.html#merge

**Comment by shunkakinoki** [comment]
@sileht thanks for the info! I really appreciate the response!
