### ISSUE TITLE
Make engine backend more scalable

### ISSUE THREAD

**Issue by sileht** [Mergifyio/mergify-engine#94]
All events of a repository must go to the same worker currently.
To hashring to dispatch the worker is static and on the wsgi side for now.
We should move it to the worker side, so we can dynamically change the number of workers.

The first step to do thing is to move to celery to be able to reconfigure on the fly the redis queues we are listening to.
Then we can use a `tooz` like library to have a dynamically hashring.

**Comment by jd** [comment]
@sileht Now that Celery is used and considering how v2 works, I think that's closeable?

**Comment by sileht** [comment]
We are good for now.
