### ISSUE TITLE
Don't wait for CI to return to update a branch

### ISSUE THREAD

**Issue by jd** [Mergifyio/mergify-engine#95]
When using strict workflow, it would be nice to update the next PR to be merged as soon as a PR is merged, without waiting for the CI to return. For example:

* dismiss_stale_reviews: false, strict: true 
* Two pull requests are opened, CI builds starts for both of them
* Both pull requests are approved, waiting for the CI build to finish
* CI build passes for the first pull request, it is up to date with master, Mergify merges it
* CI build still runs for the second pull request. When it finishes, Mergify will update the pull request with all of the changes from master, and CI build will start again for this pull request. Instead, Mergify could update the second pull request instantly as soon as it sees that it became not up-to-date. It is an approved pull request, so the only blocker for merging it is the CI build.

However, there's also one drawback: if you cancel the builds while it was at 90% and was going to fail at 95%, you won't know it was going to fail. So by retriggering the CI, you'll restart a new entire build just to know that the PR needs to be fixed, and knowing that just cost you the double amount of CI.

Obviously, that's my pessmistic side talking. If most PR pass your CI on the first run, there might be some saving. :)

**Comment by sileht** [comment]
This have been done in engine v2, we can use strict: smart or strict: True
