### ISSUE TITLE
Backport: too big failure - what does it mean and how to fix it

### ISSUE THREAD

**Issue by 0xc0170** [Mergifyio/mergify-engine#958]
I've tried to backport PR https://github.com/ARMmbed/mbed-os/pull/12785#issuecomment-617672793 - it failed with a reason: "too big". What does this reason mean ? In case of git, where git fails exactly?

When I fetched PR locally and cherry-picked the commits on top of destination branch (mbed-os-5.15 branch) without any issues - no conflicts. What exact commands backport uses?

Reading the code, here it is : https://github.com/Mergifyio/mergify-engine/blob/927b016367d05038db5f8c15efb716f0bceb76a2/mergify_engine/duplicate_pull.py#L191

Is our repo big and it cant be managed by Mergify? Where this limit comes from? Is there a way to increase the limit or find another way how PRs should be fetched?

**Comment by jd** [comment]
Hey @0xc0170 

Indeed, your repository is too big to be cloned. We had to put a limit so we don't overload our workers.
We'll remove this limit for pro subscribers, but we can't afford to spend too many resources on open source plan for now.

**Comment by 0xc0170** [comment]
OK, makes sense, will continue testing mergify.
